### ISSUE TITLE
(3) Change all endpoints to pattern

### ISSUE THREAD

**Issue by ygortgaleno** [lappis-unb/BotFlow#10]
Change all endpoints to pattern project, eg: /project/:projectId/intent and replace "names" by "ids" on endpoint paths

**Tasks**
- [x] Change project endpoints to use `ProjectId` instead of `ProjectName`
- [x] Change intent endpoints to add `/project/`
- [x] Change intent endpoints  to `ProjectId` instead of `ProjectName`
- [x] Change utter endpoints  to add `/project/`
- [x] Change utter endpoints  to `ProjectId` instead of `ProjectName`
- [ ] Change story endpoints to add `/project/`
- [ ] Change story endpoints to reference `UtterId` and `IntentId` rather than names
- [ ] Change endpoint of generate domain file

**Acceptance criteria**

- [ ] All endpoints correspond to pattern
- [ ] No item names are shown in contexts where an ID would work better
