### ISSUE TITLE
Create database-to-file parsers

### ISSUE THREAD

**Issue by rodrigocam** [lappis-unb/BotFlow#100]
Create the rest of parser that generate all files a Bot needs. (intents, stories, utters, domain, actions)

**Tasks**

- [ ] Create a utters parser 
- [ ] Create a domain parser
- [ ] Create a actions parser
- [ ] Create view to provide all the files generated for the parsers

**Acceptance criteria**

- [ ] The file validator pass with the generated files

**Comment by KalebeLopes** [comment]
Following the procedures according to #153.

**Comment by RochaCarla** [comment]
To identify where is the problem use the command rasa validate

https://legacy-docs-v1.rasa.com/user-guide/validate-files/

**Comment by KalebeLopes** [comment]
Nice! Thanks
