### ISSUE TITLE
(5) List utters

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#11]
List all utters sorted by name (A-Z)

**Tasks**

- [x] Read utters from API
- [x] Sort and show on screen
- [x] Truncate longer file names based on available screen space
- [x] Link each utter to its edit view

**Acceptance criteria**

- [x] All available utters can be seen on screen, ~properly sorted~
- [x] Edit screen loads with the correct info when an utter is clicked
- [x] Reviewed and stable code is available on the DEV environment
