### ISSUE TITLE
(5) Create "add utter" flow 

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#14]
Allow people to add new utters from the utter list.

**Tasks**

- [x] Start with an empty speech balloon
- [x] Apply same balloon editing behavior as the edit utter screen
- [x] Allow saving only when at least one balloon has content
- [ ] Disallow new utters to have an existing utter name
- [x] Save data to DB

**Acceptance criteria**

- [x] New utters are correctly added to the bot content, and updated result can be seen on DB 
- [ ] Reviewed and stable code is available on the DEV branch

**Comment by rodmaia2099** [comment]
" Disallow new utters to have an existing utter name " is mapped on #66
