### ISSUE TITLE
Remove empty balloons when inserting/editing utters

### ISSUE THREAD

**Issue by rodmaia** [lappis-unb/BotFlow#144]
When inserting or editing an utter you can have balloons that are completely empty or that only have a [space] character inside. These balloons should be:

- ignored by the front-end validation
- not saved to the database
- removed from the utter if present upon loading

A confirmation message should appear upon save saying "Balões vazios foram removidos".

With the exception of utters whose entire content is a single empty balloon. In that case, validation should continue preventing to save that utter.

**Tasks**

- [ ] TBD

**Acceptance criteria**

- [ ] Empty balloons are no longer present after saving
- [ ] Empty balloons are not loaded from the database
- [ ] Confirmation message is visible upon saving

**Comment by FranciscoHeronildo** [comment]
Working on a solution to this problem.

**Comment by rodmaia** [comment]
@FranciscoHeronildo assign the issue to yourself if you are working on it 😉

Let me know if you can expose your dev environment to the web. I’d like to test it to ensure the original idea on the issue makes sense.

**Comment by Miguel-Alves** [comment]
I have concluded this issue.
Now, empty content is no longer saved or loaded to the database. And when saving or editing an utter, they are ignored by the front-end validation.
Also, there is a confirmation message displayed to user stating this removal of empty content
