### ISSUE TITLE
Basic utter filtering

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#15]
Utter lists might get extremely long. BotFlow will allow on-the-fly filtering based on utter names.

**Tasks**

- [x] Filter the utter list
- [x] ~Highlight matching part of the name~
- [x] Allow clearing the whole filter with one click
- [x] Handle zero matches
- [x] Reset filter when people leave the utter section

**Acceptance criteria**

- [x] People can filter the utter list
