### ISSUE TITLE
Disable delete button when utter has a single balloon

### ISSUE THREAD

**Issue by rodmaia** [lappis-unb/BotFlow#150]
When an utter has a single text balloon, the delete button of that balloon should be disabled as you cannot leave an utter with zero balloons. The delete button should be reenabled once you add more balloons.

**Tasks**

- [ ] Steps to complete this task
- [ ] Steps to complete this task

**Acceptance criteria**

- [ ] Delete button is disabled when there is a single balloon
- [ ] Delete button is enabled when there are two or more balloons

**Comment by Miguel-Alves** [comment]
Reviewing this issue based on #153;

**Comment by Miguel-Alves** [comment]
This issue is very similar to #151 . And, as it happened to it's "sister", happens here either. 
This work is kind of redundant as already exists a validation that does not allow the user to delete the last content.
But, following the procedures of #153 , this issue is maintained;

**Comment by Miguel-Alves** [comment]
Solved this issue adding another validation to the button when editing utters, as described in #163 ;
Then, this issue was moved to "Awaiting Review"

**Comment by rodmaia** [comment]
> This work is kind of redundant as already exists a validation that does not allow the user to delete the last content.

See https://github.com/lappis-unb/BotFlow/issues/151#issuecomment-788993997

**Comment by Miguel-Alves** [comment]
Checked it and now I understand these needs and procedures. Anyway, I added the validation that solves this issue and a PR solving it is open

**Comment by rodmaia** [comment]
I tested it! Looks good on my end.
