### ISSUE TITLE
Disable delete button when intent has a single text field

### ISSUE THREAD

**Issue by rodmaia** [lappis-unb/BotFlow#151]
When an intent has a single text field, the delete button of that text field should be disabled as you cannot leave an intent with zero questions. The delete button should be reenabled once you add more text fields.

**Tasks**

- [ ] Steps to complete this task
- [ ] Steps to complete this task

**Acceptance criteria**

- [ ] Delete button is disabled when there is a single text field
- [ ] Delete button is enabled when there are two or more  text fields

**Comment by Miguel-Alves** [comment]
Reviewing this issue based on #153;

**Comment by Miguel-Alves** [comment]
This issue was maintained following the procedures of #153;

Although it was maintained, it asks for a redundant work and validation, since there is already a validation that doesn't allow the user to delete the last or only question, even if the button is enabled.

**Comment by Miguel-Alves** [comment]
Solved this issue as described in #162

**Comment by rodmaia** [comment]
> Although it was maintained, it asks for a redundant work and validation, since there is already a validation that doesn't allow the user to delete the last or only question, even if the button is enabled.

It's not redundant because we are exposing the actual behavior in a way people can understand, following the usability principle of Visibility of the System 😉

**Comment by Miguel-Alves** [comment]
Got it! Thanks by the answer. It makes total sense. 
The validation was added, and a PR to solve this issue is open.

**Comment by rodmaia** [comment]
I tested it! Looks good on my side.
