### ISSUE TITLE
Backlog Rework and Project Update

### ISSUE THREAD

**Issue by Miguel-Alves** [lappis-unb/BotFlow#153]
The current status of Project Backlog is way different from the actual stage of Software, in a way that it does not trully reflect the work that needs to be done. So, We identified the urgent need of reworking and updating the entire Backlog. 

We are going to review carefully every registered open issue to verify it's accuracy; 
Run the project to find bugs or others inconscistencies; 
And register every update on new issues, to make it clear the work that is being done;

.
**Tasks**

- [ ] Review carefully every registered open issue;
- [ ] Run the project to find bugs or others inconscistencies;
- [ ] Register every update on new issues;

**Acceptance criteria**

- [ ] Every registered open issue reviewed;

**Comment by mansogf** [comment]
I am currently checking the status of #95 #149 #76 #48 and will be working on these in the exposed order.

#### Checklist:

- [x] #95 
- [x] #149 
- [ ] #76 
- [ ] #48 

The revision reports already made can be visualized on the issue page.

**Comment by Miguel-Alves** [comment]
So I am currently working on issues #145 #151 #150 #122;
I am going to review them and solve those that still describe a work that needs to be done;

**Comment by AmandaMuniz** [comment]
I am currently reviewing issues #113 #28 #114 #119

**Comment by luderibeiro** [comment]
I am currently reviewing issues #148 #67 #121 #115

**Comment by KalebeLopes** [comment]
I am currently reviewing issues #142 #100

**Comment by FranciscoHeronildo** [comment]
I am currently reviewing issues #144

**Comment by AmandaMuniz** [comment]
The issue #24 was checked on Feb 24 and was closed the same day.

**Comment by leticiaarj** [comment]
I am currently reviewing issues #146 #33 #29 #35.

**Comment by Miguel-Alves** [comment]
Issue #145 was maintained and solved on #161;
So it was moved to "Awaiting Review"

**Comment by Miguel-Alves** [comment]
Issue #151 was maintained, although it is a redundant work;

**Comment by Miguel-Alves** [comment]
Solved issue #151 as described in #162 . It was also moved to "Awaiting Review"

**Comment by Miguel-Alves** [comment]
Issue #150 was maintained, but has the same observation as issue #151;

**Comment by Miguel-Alves** [comment]
Solved issue #150 adding another validation to the button when editing utters, as described in #163 ;
Then, the issue was moved to "Awaiting Review"

**Comment by Miguel-Alves** [comment]
The Issue #122 was closed, because it did not represent a valid existing error. 
@rodmaia did the check and closed the issue himelf.

**Comment by gabrielfilipe7unb** [comment]
#95 :

- There was a try to create the CI/CD using Travis but only the build stage was completed for the front-end repository.
- The CI/CD was not stated in the back-end repository.
- Initially, it was expected to develop the CI/CD with Github Actions, however, because LAPPIS infrastructure did not support it, they moved it to Gitlab CI. Due to the current status of the project and the necessity of creating a general infrastructure, it will be refactored using Travis or Github Actions.
