### ISSUE TITLE
Create Unit tests for the frontend

### ISSUE THREAD

**Issue by leticiaarj** [lappis-unb/BotFlow#155]
Perform unit tests on the frontend project, having code coverage and possible error analysis.

**Tasks**

- [ ] Test as many components and methods as possible.
- [ ] Check the return of each test and signal the team about possible errors.
- [ ] Run the tests using the instructions contained here: https://github.com/lappis-unb/BotFlow.

**Acceptance criteria**

- [ ] The tests are working.
- [ ] The project is running.

**Comment by leticiaarj** [comment]
Derived from the issue #146.
