### ISSUE TITLE
Create Unit tests for backend

### ISSUE THREAD

**Issue by leticiaarj** [lappis-unb/BotFlow#156]
Perform unit tests on the backend project, having code coverage and possible error analysis.

**Tasks**

- [ ] Using PyUnit for testing.
- [ ] Test as many methods as possible.
- [ ]  Check the return of each test and signal the team about possible errors.

**Acceptance criteria**

- [ ]  The tests are working.
- [ ] The project is running.

**Comment by leticiaarj** [comment]
Derived from the issue #146.
