### ISSUE TITLE
Configuration problem breaks dev environment

### ISSUE THREAD

**Issue by Miguel-Alves** [lappis-unb/BotFlow#157]
When running front-end dev environment we've faced a problem that is related to the configuration the project established as standard. This error happens specifically on file _url_routes.js_ when trying to import the variable REACT_APP_URL_API.

This variable is mentioned on project's _README_ file, to be set on the _docker-compose.yml_ file according to the server where the API is running. 

But, even when setting the correct server, all the requisitions made to the API are made to a broken URL. 
This error happens here:

![image](https://user-images.githubusercontent.com/30907461/109227830-b4196280-779f-11eb-8f8a-9468cae31f3a.png)
FILE: _url_routes.js_

This usage of the variable brings the adress set, but unites it with a "undefined" word before adding the rest of the path to the API. So, its breaks all the callings to the API.

Altough this is a bug that happens when using the dev environment, it does not happen when using docker.

**Tasks**

- [ ] Fix the API calling adress without breaking the docker use of it;

**Acceptance criteria**

- [ ] Dev environment can communicate with the API;
- [ ] Front-end docker continues to work correctly;

**Comment by Miguel-Alves** [comment]
So we(@AmandaMuniz) corrected this by changing the way we state the API adress;

![image](https://user-images.githubusercontent.com/30907461/109228700-fd1de680-77a0-11eb-8a38-1eb08a10c03b.png)

By doing so, we did not break the docker behaviour and corrected the communication with the API on dev environment;.
