### ISSUE TITLE
Advanced utter filtering

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#17]
Evolve utter filtering to include its content on the lookup

**Tasks**

- [ ] Filter utters based on the utter content
- [ ] Show matching part of the content in the utter list

**Acceptance criteria**

- [ ] People can filter utters by either name or content
