### ISSUE TITLE
Create basic intent editing 

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#18]
Create basic version of the Intent editing screen according to the wireframes: https://k6edxq.axshare.com/#c=2. For now, only the core behaviour will be implemented. Sidebars and main navigation will be done in separate issues.

**Tasks**

- [x] Create basic interface
- [x] Enforce a minimum of 10 training questions
- [x] Questions are added from bottom to top
- [x] Allow undo removing an question from an intent
- [x] Strip leading and trailing spaces from training questions
- [x] Strip trailing ponctuation

**Acceptance criteria**

- [x] Intents can be edited, saved and updated result seen on DB 
- [x] Infinite training questions can be added
- [x] Reviewed and stable code is available on the DEV branch
