### ISSUE TITLE
(2) List intents

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#19]
List all intents sorted by name (A-Z)

**Tasks**

- [x] Transform utter list into a reusable component
- [x] Read intents from DB
- [x] Sort and show on screen
- [x] Truncate longer file names based on available screen space
- [ ] Link each intent to its edit view

**Acceptance criteria**

- [x] All available intents can be seen on screen, properly sorted
- [ ] Edit screen loads with the correct info when an intents is clicked
- [ ] Reviewed and stable code is available on the DEV branch

**Comment by gabibguedes** [comment]
As discussed on Planning, the intent edit view will be done in another issue. The edit view for this issue will be represented only by updating the name on screen.
