### ISSUE TITLE
Deploy validator on API

### ISSUE THREAD

**Issue by BrunaNayara** [lappis-unb/BotFlow#2]
Make it possible to validate training data using the API machine and using the _RASA_ validator.

**Tasks**

- [ ] Insert [validator](https://github.com/lappis-unb/rasa/blob/validator/rasa/core/validator.py) on API 
- [ ] Make endpoint for validation

**Acceptance criteria**

- [ ] Deploy validator on API
- [ ] Be able to validate training data
- [ ] Show output log

**Comment by rodmaia2099** [comment]
Won't be necessary users will not edit source files directly
