### ISSUE TITLE
Create "add intent" flow

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#21]
Allow people to add new intents from the intent list.

**Tasks**

- [x] Start with an empty training question input box
- [x] Allow saving only when at least 10 training questions have been added
- [x] Replace empty spaces with underscores on the intent name
- [x] Disallow new intents to have an existing intent name
- [x] Save data to DB

**Acceptance criteria**

- [x] New intents are correctly added to the bot content, and updated result can be seen on DB 
- [ ] Reviewed and stable code is available on the DEV branch
