### ISSUE TITLE
Basic intent filtering

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#22]
Intent lists might get extremely long. BotFlow will allow on-the-fly filtering based on intent names.

**Tasks**

- [x] Filter the intent list
- [x] ~Highlight matching part of the name~
- [x] Allow clearing the whole filter with one click
- [x] Handle zero matches
- [x] Reset filter when people leave the intent section

**Acceptance criteria**

- [x] People can filter the intent list
