### ISSUE TITLE
Advanced intent filtering

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#23]
Evolve intent filtering to include its content on the lookup

**Tasks**

- [ ] Filter intents based on the intent content
- [ ] Show matching part of the content in the intent list

**Acceptance criteria**

- [ ] People can filter intents by either name or content
