### ISSUE TITLE
List stories

### ISSUE THREAD

**Issue by rodmaia** [lappis-unb/BotFlow#24]
List all stories sorted by name (A-Z)

**Tasks**

- [x] Read stories from DB
- [x] Sort and show story cards on screen
- [x] Link each card to its edit view

**Acceptance criteria**

- [x] All available stories can be seen on screen, properly sorted
- [x] Edit screen loads with the correct info when a story is clicked
- [x] Reviewed and stable code is available on the DEV branch

**Comment by AmandaMuniz** [comment]
I'm moving this issue to "done" because a pull request that resolves was accepted in Sep 2019.

**Comment by AmandaMuniz** [comment]
This issue was closed following the procedures according to #153.
