### ISSUE TITLE
Create basic story editing

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#26]
Create basic version of the story editing screen according to the wireframes: https://k6edxq.axshare.com/#c=2. 

**Tasks**

- [x] Create basic interface
- [x] Read data from/save data to API
- [x] List both utters and intents
- [ ] Move orphan utters and intents to the top of their respective lists
- [ ] Allow drag-and-drop of utter and intent content boxes
- [ ] Force first item to be an intent
- [ ] ~Show a usage count before each content box~
- [ ] Allow saving only when there is at least one intent and one utter
- [ ] Allow saving only if the story is different from all other stories

**Acceptance criteria**

- [ ] Stories can be edited, saved, and updated result seen on DB

**Comment by rodmaia2099** [comment]
@gabibguedes @EzequielDeOliveira please keep in mind that removing an item from a story won't trigger an "undo" snackbar. The content is never truly lost, as it's on the utter/intent list, so there is no need to confirm anything. Just make it disappear.
