### ISSUE TITLE
Add dialog simulation to the edit story screen

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#27]
Display a simulation of the current story based on active intents and utters.

**Tasks**

- [ ] Show an "incoming" speech balloon with a training question (chosen randomly) from the intent
- [ ] Show an "outgoing" speech balloon for each matching balloon in the utter
- [ ] Show a single "outgoing" speech balloon for utters that have multiple balloons as alternatives (choose randomly)
- [ ] Update the simulation whenever the content boxes in the main area change

**Acceptance criteria**

- [ ] People have a clear idea of how the dialog will flow based on the simulation alone
