### ISSUE TITLE
 Create "add story" flow

### ISSUE THREAD

**Issue by rodmaia** [lappis-unb/BotFlow#28]
Allow people to add new stories from the story list.

**Tasks**

- [x] Duplicate the "edit story" flow and strip the loading of data
- [x] Disallow new stories to have an existing story name
- [ ] ~Allow saving only if the story is different from all other stories~
- [x] Save data to DB

**Acceptance criteria**

- [x] New stories are correctly added to the bot content, and updated result can be seen on DB

**Comment by AmandaMuniz** [comment]
Following the procedures according to #153.

**Comment by AmandaMuniz** [comment]
After checking this issue, I wasn't able to find a pull request that had resolved it. However, there are commits on branch master connected to the work described on this issue. And while running the project, the flow works correctly, and the new data can be found in the database. This issue will be moved to done and will be closed.
