### ISSUE TITLE
Clone story

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#29]
Allow people to clone a story to create new stories quicker

**Tasks**

- [ ] Start an "add story" flow, and prepopulate the content with a copy of the original story
- [ ] Add a "_2" (or equivalent trailing counter) to the story name, to avoid duplication
- [ ] Allow saving only if the story is different from all other stories

**Acceptance criteria**

- [ ] New story is correctly added to the bot content, and updated result can be seen on DB
