### ISSUE TITLE
(8) Study the possibility of using PLOC architecture

### ISSUE THREAD

**Issue by gabibguedes** [lappis-unb/BotFlow#3]
Check the flow of deployment on Tais, and see if it's possible to use the coach method to train and deploy a trial version of the bot made on BotFlow.

**Tasks**

- [x] Analyse the PLOC architecture on Tais, and how the coach is done
- [x] Analyse the possibilities of using coach on another machine
- [x] Decide the communication between API and coach
- [x] Decide how this architecture will work
- [x] Document the architecture chosen

**Acceptance criteria**

- [ ] The architecture is valid
- [ ] The architecture is documented

**Comment by rodrigocam** [comment]
The architecture proposed is a webhook communication between BotFlowAPI and the Bot, the architecture works as follows:
1 - At BotFlowAPI we have a variable in `settings.py` called *WEBHOOKS_URLS*, that is a list of urls that will be notified when a change occur in a project, intent, stories or utter.

2 - The BotFlowAPI will make a post request with the url, used to get the new file, in the body. E.g. `https://botflowapi.com/file/stories/1` in this link is possible get the stories file of the project with id 1.

3 - The Bot will have a very tiny server listen to the post requests from BotFlowAPI and it will be responsible to get the new file and save as a file in the operating system.

4 - The only responsible of BotFlowAPI is to notify who is on the list, what others do with this notification is not a concern.

State of the implementation: Actually the webhooks of the `intent` file and the `stories` file are working, and to do that a parser for stories and a parser for intents were made. What this parsers do is to get information from the database and format in `markdown` or `yml` syntax.

**Comment by rodrigocam** [comment]
The next step when the PR was accepted is to make the code on the Bot side application, I already made a demo and I can implement in the next sprint.
