### ISSUE TITLE
(3) Basic utter deleting

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#30]
**Tasks**

- [x] Allow people to undo Delete
- [x] Remove utter from DB

**Acceptance criteria**

- [x] Deleted utters are removed from the bot content, and updated result can be seen on DB

**Comment by rodmaia2099** [comment]
I updated the prototype with the Delete flow, only for utters

**Comment by KahCosta** [comment]
Great!
