### ISSUE TITLE
Basic intent deleting

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#31]
**Tasks**

- [ ] Allow undo deletion
- [ ] Remove intent from DB

**Acceptance criteria**

- [ ] Deleted intents are removed from the bot content, and updated result can be seen on DB
