### ISSUE TITLE
Basic story deleting

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#32]
**Tasks**

- [ ] Confirm request to delete
- [ ] Remove story from DB

**Acceptance criteria**

- [ ] Deleted stories are removed from the bot content, and updated result can be seen on DB

**Comment by rodmaia** [comment]
@Miguel-Alves did somebody reviewed this issue in the process of #153?
