### ISSUE TITLE
Add utter and intent filtering to edit story screen

### ISSUE THREAD

**Issue by rodmaia** [lappis-unb/BotFlow#34]
**Tasks**

- [ ] Reuse utter and intent filtering from their respective lists
- [ ] Apply same filter for both utter and intent lists

**Acceptance criteria**

- [ ] Utters and intents in the story edit screen can be easily filtered

**Comment by luderibeiro** [comment]
Following the procedures according to #153, it was checked that this issue was already solved.
@rodmaia please verify if it is working correctly

**Comment by rodmaia** [comment]
Confirmed working
