### ISSUE TITLE
Basic story filtering

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#35]
BotFlow will allow on-the-fly filtering based on names of utters, intents or stories.

**Tasks**

- [ ] Filter the story list
- [ ] Highlight matching part of the name
- [ ] Allow clearing the whole filter with one click
- [ ] Handle zero matches
- [ ] Reset filter when people leave the story list

**Acceptance criteria**

- [ ] People can filter the story list

**Comment by rodmaia** [comment]
Did a quick check and the behavior seems mostly correct. We will need a different highlight color as the orange doesn't stand out. I suggest: #1b58ff.
