### ISSUE TITLE
Advanced story filtering

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#36]
Evolve story filtering (done in #35) to include its content on the lookup

**Tasks**

- [ ] Filter stories based on the content of utters and intents
- [ ] Show matching part of the content in the story card list

**Acceptance criteria**

- [ ] People can filter stories by either name or content
