### ISSUE TITLE
(2) Fix multiple balloons behavior on utter API endpoints

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#38]
(Continuation of #8)

Change behaviour to allow both multiple sequential balloons and multiple alternative balloons.

**Tasks**

- [x] Change utter endpoint structure
- [x] Show multiple balloons as string arrays - order of balloons matches order of strings in the array
- [x] Consider removing the "order" field

**Acceptance criteria**

- [x] Any utter can have more than one text (balloon)
- [ ] Sequential and alternative-type utters can be clearly identified 
- [x] The YML file can be generated with multiple text utters

**Comment by gabibguedes** [comment]
change from utterText to alternativeText or something similar

**Comment by rodmaia2099** [comment]
>  gabibguedes commented 1 hour ago 
> change from utterText to alternativeText or something similar

Captured on #48

**Comment by rodmaia2099** [comment]
Changes available on [PR 6 at the API repo](https://github.com/lappis-unb/BotFlowAPI/pull/6)
