### ISSUE TITLE
(5) Create basic utter editing

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#4]
Create basic version of the Utter editing screen according to the wireframes: https://k6edxq.axshare.com/#c=2. For now, only the core behaviour will be implemented. Sidebars and main navigation will be done in a separate issue.

**Tasks**

- [x] Create basic interface
- [x] Read data from the API using the correct format (according to #8)
- [ ] Save data to the API using the correct format (according to #8)
- [x] Handle multiple balloons in the correct order
- [ ] Handle using ballloons as alternatives
- [x] Balloons are added from top to bottom
- [x] The "next balloon" box is always present, regardless of the number of existing balloons
- [x] Confirm removing balloon from utter
- [x] Remove confirm/cancel buttons when editing utter text
- [ ] Remove the "idle" state of a balloon
- [x] Rename the add balloon button to "New response balloon"

**Acceptance criteria**

- [ ] Utters can be edited, saved and updated result seen on DB 
- [x] Infinite balloons can be added
- [ ] Reviewed and stable code is available on the DEV branch

**Comment by KahCosta** [comment]
Utter Create box and button to delete created box

**Comment by rodmaia2099** [comment]
What about them?

**Comment by KahCosta** [comment]
@rodmaia2099 a Caixa de edição, o botão de deletar, o botão de adicionar já estão implementados

**Comment by KahCosta** [comment]
![image](https://user-images.githubusercontent.com/30934827/59569749-5c3ad680-9064-11e9-9fe5-d38dbd167e43.png)

**Comment by KahCosta** [comment]
![image](https://user-images.githubusercontent.com/30934827/59569754-6fe63d00-9064-11e9-975f-560487fbeb89.png)

**Comment by KahCosta** [comment]
![image](https://user-images.githubusercontent.com/30934827/59569772-8f7d6580-9064-11e9-84cc-4056063181c5.png)

**Comment by rodmaia2099** [comment]
We need to evaluate if altering the text inside the balloon should be a modal operation

**Comment by rodmaia2099** [comment]
Changing the text of a balloon should *not* be a modal operation. We need to remove the idle state, and the confirm/cancel buttons. An utter balloon should always be in edit state.

Additionally, the button to include another balloon should have a label that doesn't cause confusion with the main *save* button.

**Comment by KahCosta** [comment]
![image](https://user-images.githubusercontent.com/30934827/60177119-7441f100-97ee-11e9-9657-44e9bc7b2aca.png)
![image](https://user-images.githubusercontent.com/30934827/60177138-80c64980-97ee-11e9-88e7-66ca3eea4236.png)

Label changed in button Add
Removed confirm/cancel buttons

**Comment by rodmaia2099** [comment]
@KahCosta please send a PR with the changes you made

**Comment by KahCosta** [comment]
Done @rodmaia2099 
I opened PR and assigned @gabibguedes

**Comment by rodmaia2099** [comment]
Missing tasks and changes mapped to #49
