### ISSUE TITLE
(1) Create a proper Readme

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#41]
Add relevant info to the Readme page on the Botflow repo.

**Tasks**

- [x] Add Botflow URLs to the header 
- [x] Add Botflow URLs to the Readme
- [x] Add relevant information (???)

**Acceptance criteria**

- [x] Relevant info is available on the Readme page

**Comment by rodmaia2099** [comment]
I added a template structure to the readme based on feedback from @joenio

**Comment by KahCosta** [comment]
Great @rodmaia2099 !
I'm going to start producing the descriptions
