### ISSUE TITLE
Document API endpoit usage

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#48]
Some endpoints have a more complex usage pattern. Utters, for example, can have one or more content alternatives, and each alternative can have multiple strings (balloons).

This type of usage needs to be clearly documented so new contributors know how to explore the full potential of the API.

**Tasks**

- [ ] Steps to complete this task
- [ ] Steps to complete this task

**Acceptance criteria**

- [ ] Developers outside the Botflow team know how to use the API just by reading the documentation

**Comment by gabrielfilipe7unb** [comment]
Following the procedures according to #153.
