### ISSUE TITLE
(5)Improve utter editing behavior

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#49]
(Continuation of #4)

**Tasks**

- [x] Save data to the API using the correct format (according to #8)
- [x] Handle using ballloons as alternatives
- [x] Remove the "idle" state of a balloon -> they should be always editable
- [x] Disable **Save** button until any changes are made on the content
- [x] Disable **Save** button if the utter is completely empty

**Acceptance criteria**

- [x] Utters can be edited, saved, updated, and the result can seen on the interface by reloading the utter
- [x] Reviewed and stable code is available on the DEV environment
