### ISSUE TITLE
Create API endpoint for intents

### ISSUE THREAD

**Issue by BrunaNayara** [lappis-unb/BotFlow#5]
Create API endpoint to download intents file

**Tasks**

- [ ] Create API endpoint
- [ ] Get all intents from database
- [ ] Write all intents in md file

**Acceptance criteria**

- [ ] Be able to download intents file
- [ ] Document on swagger

**Comment by rodmaia2099** [comment]
Duplicate of #9
