### ISSUE TITLE
(2) Show active utter on the list

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#50]
Identify the utter being edited on the utter list. Suggestion: make it bold.

**Tasks**

- [ ] Steps to complete this task
- [ ] Steps to complete this task

**Acceptance criteria**

- [ ] Active utter is clearly identifiable on the list
