### ISSUE TITLE
(5) Handle invalid utter names

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#51]
People might use invalid characters on utter names, such as spaces, tildes, cedillas etc. This is a problem for Rasa to process utter names. 

BotFlow needs to handle that both on the frontend as on the backend, and replace those characters by valid ones seamlessly.

**Tasks**

- [ ] Steps to complete this task
- [ ] Steps to complete this task

**Acceptance criteria**

- [ ] Special characters don't break generated training files

**Comment by gabibguedes** [comment]
In the API should we just give an error when a new utter is created with unaccepted characters or we replace then by accepted characters?

**Comment by gabibguedes** [comment]
Is the API verification necessary if there is already a verification in the frontend?

**Comment by rodmaia2099** [comment]
>In the API should we just give an error when a new utter is created with unaccepted characters or we replace then by accepted characters?

We should probably throw an error to prevent people from using the unaccepted name on their end. If we simply replace the characters we might run into inconsistencies.

>Is the API verification necessary if there is already a verification in the frontend?
Definitely! The API may be used independently from the frontend so it should be robust and decoupled.
