### ISSUE TITLE
(5)Refactor utters screen file

### ISSUE THREAD

**Issue by gabibguedes** [lappis-unb/BotFlow#52]
The file structure should be refactored into two different components, so when the side menu is clicked on a specific utter, the dialog updates according

**Tasks**

- [x] Create a separate utter menu;
- [x] Links, each menu item with the dialog page, passing the utter content

**Acceptance criteria**

- [x] The utters page updates with the selected utter
