### ISSUE TITLE
(3) Sort utter names alphabetically

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#53]
Sort utter names alphabetically (A-Z) on the utter list.

**Tasks**

- [ ] Steps to complete this task
- [ ] Steps to complete this task

**Acceptance criteria**

- [x] Utters list is alphabetically sorted on the DEV environment
