### ISSUE TITLE
(13) Deploy front environments 

### ISSUE THREAD

**Issue by gabibguedes** [lappis-unb/BotFlow#6]
Deploy Beta and Prod environments.

**Tasks**

- [x] Create Machine
- [x] Install dependencies
- [x] Beta points to devel
- [x] Prod points to master
- [x] Configure NGINX
- [x] Decide and integrate CI (Gitlab, Watch Tower...)

**OBS.:** Diniz suggestion is Watch Tower

**Acceptance criteria**

- [x] The prod is working and updating correctly
- [x] The beta is working and updating correctly

**Comment by KahCosta** [comment]
Virtual Machine Created
IP: 10.0.0.150

**Comment by KahCosta** [comment]
Next step:
- Create Docker for production and homologation with correct targeting tag
- Configure NGINX
- Apply Watch Tower to Automatic continuous deploy

**Comment by BrunaNayara** [comment]
[NGINX configuration tutorial](https://github.com/arthurbdiniz/docker-letsencrypt-nginx)

**Comment by BrunaNayara** [comment]
@KahCosta já instalei docker, git, e outras coisas menores na máquina. E estudei um pouco sobre o NGINX. Na segunda devo tirar algumas dúvidas com o Diniz e documentar o processo de subir as coisas na máquina

**Comment by KahCosta** [comment]
beleza @BrunaNayara 
Vou ver como criar as tags no docker para direcionamento de deploy tanto de homologação quanto de produção

**Comment by KahCosta** [comment]
Ambiente de Homologação
IP: 10.0.0.150
Domínio homologação: botflow.lappis.rocks
Domínio API: botflow.api.lappis.rocks/api-docs

**Comment by KahCosta** [comment]
Ambiente de Desenvolvimento
IP: 10.0.0.151
Domínio Dev: botflow.dev.lappis.rocks

**Comment by KahCosta** [comment]
Watch Tower configurado no ambiente de Prod e API

**Comment by KahCosta** [comment]
Watch Tower configurado no ambiente de Dev
