### ISSUE TITLE
(3) Populate homolog and devel database

### ISSUE THREAD

**Issue by gabibguedes** [lappis-unb/BotFlow#64]
The homolog and devel database should be populated with real content from Tais. This is important for testing the platform with @palomacmamede  

**Tasks**

- [ ] Erase the DB content in devel
- [ ] Add utters in devel
- [ ] Add intents in devel
- [ ] Erase the DB content in homolog
- [ ] Add utters in homolog
- [ ] Add intents in homolog

**Acceptance criteria**

- [ ] BotFlow can be tested and works with real content in both homolog and devel

**Comment by gabibguedes** [comment]
It's better to create a script that populates with the existing files, so it can be done as much times as needed.

**Comment by gabibguedes** [comment]
The API is going to be updated next sprint, therefore its better to postpone this issue so we don't have to update the scripts later. 
I was using the `populateDB` branch for doing the scripts.

**Comment by rodmaia** [comment]
Issue no longer relevant. Replaced by #147
