### ISSUE TITLE
Prevent duplicated names for utters or intents

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#66]
Prevent BotFlow from saving utters and intents with the same name and show an error message.

**Tasks**

- [x] Steps to complete this task
- [x] Steps to complete this task

**Acceptance criteria**

- [x] Conditions to mark this task complete
- [x] Conditions to mark this task complete

**Comment by EzequielDeOliveira** [comment]
This issue is done with the issue #73 on the UtterArchitecture branch
