### ISSUE TITLE
Dialog component won't reload

### ISSUE THREAD

**Issue by gabibguedes** [lappis-unb/BotFlow#68]
The dialog component doesn't reload dynamically. Currently the reload is being forced by the `window.location.reload()` method, but this method shouldn't be necessary. 

**Tasks**

- [x] Verify why the dialog wont reload
- [x] Make the changes necessary so it can be reloaded dynamically.

**Acceptance criteria**

- [x] The `window.location.reload()` method is no longer necessary

**Comment by gabibguedes** [comment]
This branch still has a few `window.location.reload()` methods on files `SideBar/index.js` and `Utters/index.js`. When remove this remaining methods the page doesn't update anymore.

**Comment by rodmaia2099** [comment]
@gabibguedes is this still a problem? Or can we close it due to the changes in the architecture?
