### ISSUE TITLE
Refactor the Utter page according to the new architecture

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#73]
**Tasks**

- [x] Bring the new architecture to the a separate branch
- [x] Refactor the Utter page to the new architecture
- [x] Apply the same behaviour for listing utters as the one described in #11, #50 and #53    
- [x] Apply the same behaviour for utter editing as described in #4, #49, #51 
- [x] Apply the same behaviour for utter creation as described in #14 and #63 
- [x] Apply the same behaviour for utter deletion as described in #30 
- [x] Fix #66 

**Acceptance criteria**

- [ ] New utter page can be tested on the Dev environment with a feature set equal to the current version
