### ISSUE TITLE
Refactor the Intent list according to the new architecture

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#75]
**Tasks**

- [x] Refactor the Intent list page to the new architecture
- [x] Apply the same behaviour for listing utters as the one described in #19

**Acceptance criteria**

- [ ] New intent list can be tested on the Dev environment with a feature set equal to the current version
