### ISSUE TITLE
Improve API labels

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#78]
**Tasks**

- [x] Switch to snake case
- [x] Replace redundancies on label names (eg: Utter {utterName} -> Utter {name}
- [x] Update BotFlow code accordingly

**Acceptance criteria**

- [ ] Updated API works as well as the old version

**Comment by rodmaia2099** [comment]
@eduardonunes2525 any other tasks to be added here?
