### ISSUE TITLE
(2) Change model for utterances

### ISSUE THREAD

**Issue by BrunaNayara** [lappis-unb/BotFlow#8]
Describe your feature request

**Tasks**

- [x] Add multiple alternative texts to an utterance (model)
- [x] Add order to utterance texts (model)
- [x] Change domain file generation

**Acceptance criteria**

- [x] Be able to save multiple-texts utterances
- [x] Be able to download domain file with multiple-texts utterances
