### ISSUE TITLE
Review the need for IDs in utter texts

### ISSUE THREAD

**Issue by EzequielDeOliveira** [lappis-unb/BotFlow#83]
talk about the id contained in each text in utters

**Tasks**

- [x] Steps to complete this task
- [x] Steps to complete this task

**Acceptance criteria**

- [ ] Conditions to mark this task complete
- [ ] Conditions to mark this task complete
