### ISSUE TITLE
Transfer all sorting from the frontend to the API

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/BotFlow#84]
**Tasks**

- [x] Sort utters list
- [x] Sort intent list

**Acceptance criteria**

- [x] Utters and Intents always return a sorted list alphabeticaly
